LightSaber:
  cost: 1
  stack: 1
  inventory count: 100
  purchase price: 0

Acorn:
    cost: 20
    stack: 1
    inventory count: 0
    purchase price: 10

Amber:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 30

AmberPearl:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 20

BarleyWine:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 50

BeechSeeds:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 1

BirchSeeds:
    cost: 15
    stack: 1
    inventory count: 0
    purchase price: 7

BlackMetal:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 50

BlackSoup:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 15

BloodPudding:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 60

Bloodbag:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 3

Blueberries:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 2
    
BoarJerky:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 6
    
BombOoze:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 50
    
BoneFragments:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 1
    
Bread:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 25
    
Bronze:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 17
    
BronzeNails:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 4

Carrot:
    cost: 6
    stack: 1
    inventory count: 0
    purchase price: 3

CarrotSeeds:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 1
    
CarrotSoup:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 10
    
Chain:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 13

Chitin:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 40
    
Cloudberry:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 4
    
Coal:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 2
    
CookedMeat:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 2
    
CookedDeerMeat:
    cost: 7
    stack: 1
    inventory count: 5
    purchase price: 4
    
CookedLoxMeat:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 6
    
CookedWolfMeat:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 5
    
Copper:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 3
    
Crystal:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 18
    
Dandelion:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 2
    
DeerHide:
    cost: 9
    stack: 1
    inventory count: 5
    purchase price: 4
    
DeerStew:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 7
    
DragonEgg:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 60
    
DragonTear:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 100
    
ElderBark:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 4
    
Eyescream:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 12

Feathers:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 3

FineWood:
    cost: 12
    stack: 1
    inventory count: 5
    purchase price: 5

FishRaw:
    cost: 10
    stack: 1
    inventory count: 0
    purchase price: 10

FishCooked:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 15

FishWraps:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 30

Flint:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 4
    
FreezeGland:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 7
    
GoblinTotem:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 28
    
GreydwarfEye:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 2
    
Guck:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 20
    
HardAntler:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 20
    
Honey:
    cost: 7
    stack: 1
    inventory count: 5
    purchase price: 3
    
Iron:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 30
    
IronNails:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 5
    
LeatherScraps:
    cost: 5
    stack: 1
    inventory count: 5
    purchase price: 1
    
LinenThread:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 4

LoxPelt:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 9

LoxPie:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 70

NeckTail:
    cost: 5
    stack: 1
    inventory count: 0
    purchase price: 2

MeadFrostResist:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 25

MeadHealthMedium:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 30

MeadHealthMinor:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 25

MeadPoisonResist:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 25

MeadStaminaMedium:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 25

MeadStaminaMinor:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 24

MeadTasty:
    cost: 36
    stack: 1
    inventory count: 5
    purchase price: 20

MinceMeatSauce:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 6

Mushroom:
    cost: 3
    stack: 1
    inventory count: 5
    purchase price: 1

MushroomBlue:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 3

MushroomYellow:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 2

NeckTailGrilled:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 2

Needle:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 3

Obsidian:
    cost: 0
    stack: 1
    inventory count: 5
    purchase price: 5

OnionSoup:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 8

Ooze:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 3

PineCone:
    cost: 10
    stack: 1
    inventory count: 0
    purchase price: 4

Pukeberries:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 1

QueenBee:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 55

QueensJam:
    cost: 26
    stack: 1
    inventory count: 20
    purchase price: 8

ArmorRagsLegs:
    cost: 26
    stack: 1
    inventory count: 0
    purchase price: 0

ArmorRagsChest:
    cost: 26
    stack: 1
    inventory count: 0
    purchase price: 0

Raspberry:
    cost: 2
    stack: 1
    inventory count: 20
    purchase price: 1

Resin:
    cost: 2
    stack: 1
    inventory count: 20
    purchase price: 1

RoundLog:
    cost: 7
    stack: 1
    inventory count: 20
    purchase price: 3

Ruby:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 50

Sausages:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 15

SerpentMeat:
    cost: 135
    stack: 1
    inventory count: 0
    purchase price: 0

SerpentMeatCooked:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 60

SerpentScale:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 50

SerpentStew:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 40

SharpeningStone:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 10

Silver:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 45

SilverNecklace:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 150

Stone:
    cost: 3
    stack: 1
    inventory count: 20
    purchase price: 1

SurtlingCore:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 1

Tar:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 10

Thistle:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 2

Tin:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 3

TrollHide:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 2

TrophyAbomination:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 50

TrophyBlob:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 4

TrophyBoar:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 2

TrophyBonemass:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 160

TrophyCultist:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 25

TrophyDeathsquito:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 22

TrophyDeer:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 5

TrophyDragonQueen:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 200

TrophyDraugr:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 10

TrophyDraugrElite:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 12

TrophyEikthyr:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 80

TrophyFenring:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 16

TrophyForestTroll:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 20

TrophyFrostTroll:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 25

TrophyGoblin:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 20

TrophyGoblinBrute:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 39

TrophyGoblinKing:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 240

TrophyGoblinShaman:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 70

TrophyGreydwarf:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 3

TrophyGreydwarfBrute:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 8

TrophyGreydwarfShaman:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 6

TrophyGrowth:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 50

TrophyHatchling:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 27

TrophyLeech:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 18

TrophyLox:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 82

TrophyNeck:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 1

TrophySerpent:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 98

TrophySGolem:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 108

TrophySkeleton:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 3

TrophySkeletonPoison:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 5

TrophySurtling:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 12

TrophyTheElder:
    cost: 0
    stack: 1
    inventory count: 20
    purchase price: 120

TrophyUlv:
    cost: 0
    stack: 1
    inventory count: 50
    purchase price: 26

TrophyWolf:
    cost: 0
    stack: 1
    inventory count: 50
    purchase price: 24

TrophyWraith:
    cost: 0
    stack: 1
    inventory count: 50
    purchase price: 16

TurnipStew:
    cost: 0
    stack: 1
    inventory count: 50
    purchase price: 15

WitheredBone:
    cost: 0
    stack: 1
    inventory count: 0
    purchase price: 5

WolfFang:
    cost: 0
    stack: 1
    inventory count: 0
    purchase price: 6

WolfJerky:
    cost: 0
    stack: 1
    inventory count: 0
    purchase price: 4

WolfPelt:
    cost: 0
    stack: 1
    inventory count: 0
    purchase price: 4

Wood:
    cost: 3
    stack: 1
    inventory count: 0
    purchase price: 1

YagluthDrop:
    cost: 0
    stack: 1
    inventory count: 0
    purchase price: 121